"""Add ip_address column to users table

Revision ID: 1190ef2dc0a5
Revises: 
Create Date: 2025-03-05 23:49:49.509049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1190ef2dc0a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
